config/routes.rb
Rails.application.routes.draw do
  root 'meetings#index'
  get '/meetings/calendar' => 'meetings#calendar'
  resources :meetings do
    member do
      get :destroyAll
    end
  end
  resources :rooms
  resources :home, only: [:index]
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/meeting.rb
require 'date'
class Meeting < ApplicationRecord
  has_and_belongs_to_many :users
  belongs_to :room
  validate :check_capacity, :check_slot, :date_check
  validates :name, presence: true

  def check_capacity
    capacity_pluck = Room.select(:capacity).where(id: room_id).pluck(:capacity)
    capacity = capacity_pluck.join.to_i
    users = user_ids.count + 1
    if(users>capacity)
        errors.add(:user_ids, "Capacity of this room is just #{capacity}")
    end
  end

  def check_slot
    c=Meeting.all.where(room_id: room_id).where('start_time <= ? AND end_time >= ?', start_time, start_time).where('start_time <= ? AND end_time >= ?', end_time, end_time).count
    if(c==0)
    else
      errors.add(:start_time, "Slot Booked")
    end
  end

  def date_check
    if start_time >= end_time || start_time.to_date != end_time.to_date
      errors.add(:start_time, "Incorrect date time choice!!")
    end
  end
end

app/models/room.rb
class Room < ApplicationRecord
    has_many :meetings, :dependent => :delete_all
    has_many :users, through: :meetings
    validates :name, :capacity, presence: true

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         has_and_belongs_to_many :meetings, dependent: :destroy
  
  validate :check_email

  def check_email
    if email.include? 'commutatus.com'
    else
      errors.add(:email, 'should be of a commutatus employee')
    end
    
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authenticate_user!
    def after_sign_in_path_for(resource)
        if(current_user.admin == true )
          home_index_path
        else
          root_path
        end
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :must_be_admin

  def index
    @meetings = Meeting.all
    @users = User.all
  end
  private
  def must_be_admin
    unless current_user.admin?
        redirect_to meetings_path, alert: 'You do not have access'
    end
  end
end

app/controllers/meetings_controller.rb
class MeetingsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_meeting, only: [:show, :edit, :update, :destroy, :destroyAll]

  # GET /meetings
  # GET /meetings.json
  def index      
      @meetings = current_user.meetings
      @meetings_today = current_user.meetings.where("DATE(start_time) = ?", Date.today)
      @meetings_upcoming = current_user.meetings.where("DATE(start_time) > ?", Date.today)
      @meetings_previous = current_user.meetings.where("DATE(start_time) < ?", Date.today)
  end

  # GET /meetings/1
  # GET /meetings/1.json
  def show
  end

  # GET /meetings/new
  def new
    @meeting = Meeting.new
  end

  # GET /meetings/1/edit
  def edit
  end

  # POST /meetings
  # POST /meetings.json
  def create
    @meeting = Meeting.new(meeting_params)
    # raiseStandardError
    respond_to do |format|
      if @meeting.save
        @meeting.users << current_user
        format.html { redirect_to meetings_url, notice: 'Meeting was successfully created.' }
        format.json { render :show, status: :created, location: @meeting }
        ActionMailer::Base.smtp_settings = {
          :address              => "smtp.gmail.com",
          :port                 => 587,
          :user_name            => 'harshwardhan@commutatus.com',
          :password             => 'ujnkhjbqfiggiszh',
          :authentication       => "plain",
          :enable_starttls_auto => true
        }
        MeetingMailer.with(meeting: @meeting, users: @meeting.users).meeting_scheduled.deliver_now
      else
        format.html { render :new }
        format.json { render json: @meeting.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /meetings/1
  # PATCH/PUT /meetings/1.json
  def update
    respond_to do |format|  
      if @meeting.update(meeting_params)
        format.html { redirect_to @meeting, notice: 'Meeting was successfully updated.' }
        format.json { render :show, status: :ok, location: @meeting }
      else
        format.html { render :edit }
        format.json { render json: @meeting.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /meetings/1
  # DELETE /meetings/1.json
  def destroy
    current_user.meetings.delete(@meeting)
    respond_to do |format|
      format.html { redirect_to meetings_url, notice: 'You successfully opted out of the meeting' }
      format.json { head :no_content }
    end
  end

  def calendar
    @meetings = current_user.meetings
  end

  def destroyAll
    @meeting.delete

    respond_to do |format|
      format.html { redirect_to home_index_path, notice: 'Meeting was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_meeting
      @meeting = Meeting.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def meeting_params
      params.require(:meeting).permit(:name, :start_time, :end_time, :room_id, user_ids: [])
    end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :set_room, only: [:show, :edit, :update, :destroy]
  before_action :must_be_admin

  

  # GET /rooms
  # GET /rooms.json
  def index
    @rooms = Room.all
  end

  # GET /rooms/1<<<<<<<<<<       
  # GET /rooms/1.json
  def show
  end

  # GET /rooms/new
  def new
    @room = Room.new
  end

  # GET /rooms/1/edit
  def edit
  end

  # POST /rooms
  # POST /rooms.json
  def create
    @room = Room.new(room_params)

    respond_to do |format|
      if @room.save
        format.html { redirect_to @room, notice: 'Room was successfully created.' }
        format.json { render :show, status: :created, location: @room }
      else
        format.html { render :new }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rooms/1
  # PATCH/PUT /rooms/1.json
  def update
    respond_to do |format|
      if @room.update(room_params)
        format.html { redirect_to @room, notice: 'Room was successfully updated.' }
        format.json { render :show, status: :ok, location: @room }
      else
        format.html { render :edit }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rooms/1
  # DELETE /rooms/1.json
  def destroy
    @room.destroy
    respond_to do |format|
      format.html { redirect_to rooms_url, notice: 'Room was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_room
      @room = Room.find(params[:id])
    end

    def must_be_admin
      unless current_user.admin?
          redirect_to meetings_path, alert: 'You do not have access'
      end
    end

    # Only allow a list of trusted parameters through.
    def room_params
      params.require(:room).permit(:name, :capacity)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def readable_time(time)
        time.strftime("%b %d, %I:%M%P")
    end

    def author_of(record)
        user_signed_in? && current_user.id == record.user_id
    end

    def admin?
        user_signed_in? && current_user.admin?
    end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/meetings_helper.rb
module MeetingsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/home/index.html.erb
<h2>ADMIN PANEL</h2>
<div class = 'admin-tab ml-2 mr-2 mb-4'>
    <div class = 'panel-tab'>
        <table class = 'table'>
            <thead class= 'thead-dark'>
                <tr>
                <th scope = 'col'>Name</th>
                <th scope = 'col'>Begins at</th>
                <th scope = 'col'>End at</th>
                <th scope = 'col'>Room</th>
                <th scope = 'col' colspan="2"></th>
                </tr>
            </thead>

            <tbody>
                <% @meetings.each do |meeting| %>
                <tr>
                    <td><%= meeting.name %></td>
                    <td><%= readable_time(meeting.start_time) %></td>
                    <td><%= readable_time(meeting.end_time) %></td>
                    <td><%= meeting.room.name %></td>
                    <td><%= link_to 'Destroy', destroyAll_meeting_path(meeting), data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %></td>
                </tr>
                <% end %>
            </tbody>
        </table>
    </div>
    <div class = 'panel-tab'>
    <% @users.each do |user| %>
        <div class="card user-card">
            <div class="card-body">
                <h5 class="card-title"><strong><%= user.email %></strong></h5>
                <div class="dropdown">
                    <button class="btn btn-success  dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Meetings
                    </button>
                    <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                        <% user.meetings.each do |m| %>
                            <%= link_to m.name,m, class: 'dropdown-item' %>
                        <% end %> 
                    </div>
                </div>
            </div>
        </div>
    <% end %>
    </div>
</div>

<%# <div class = 'buttons'>

<%= link_to 'New Room', new_room_path, class: 'btn btn-dark' %>
<%# <%= link_to 'Your Meetings', meetings_path, class: 'btn btn-info' %> 

<%# </div> %> 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>YourMeetingApp</title>
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" crossorigin="anonymous"></script>
  <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css' %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

  <nav class="navbar navbar-expand-md navbar-dark bg-dark">
    <a class="navbar-brand" href="/">Your Meeting Application</a>
    <div class="collapse navbar-collapse" id="navbarsExampleDefault">
      <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <%= link_to "Admin Panel", home_index_url, class: "nav-link" if admin? %>
      </li>
      <li class="nav-item">
        <%= link_to "All Meetings", root_path, class: 'nav-link' if user_signed_in?%>
      </li>
      <li class="nav-item">
        <%= link_to "All Rooms", rooms_path, class: 'nav-link' if admin? %>
      </li>
    </ul>
    <% if user_signed_in? %>
      <strong class='email-address'> Logged in as <%= current_user.email %></strong>
    <%end%>
    <ul class="navbar-nav nav">
    <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Account Settings
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <% if user_signed_in? %>
            <%= link_to 'Edit profile', edit_user_registration_path, :class => 'dropdown-item' %>
            <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'dropdown-item'  %>
          <% else %>
            <%= link_to "Sign up", new_user_registration_path, :class => 'dropdown-item'  %> 
            <%= link_to "Login", new_user_session_path, :class => 'dropdown-item'  %>
          <% end %>
        </div>
      </li>
    </ul>
      </div>
  </nav>

<% if notice %>
  <p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>
<% if admin? %>
  <p class="alert alert-success">Welcome Admin</p>
<% end %>
<div class="container">
    <%= yield %>
    </div>
  </body>
</html>

app/views/meetings/_form.html.erb
  <% if meeting.errors.any? %>
    <div id="error_explanation">  
        <% meeting.errors.full_messages.each do |message| %>
          <div class = 'alert alert-danger'><%= message %></div>
        <% end %> 
    </div>
  <% end %>
<div class="card" style="width: 27rem;">
  <div class="card-body">
    <h4 class="card-title text-center"><strong>Create Meeting</strong></h4>
    <%= form_with(model: meeting, local: true) do |form| %>
  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field(:name, {:class => 'form-control'}) %>
  </div>

  <div class="form-group">
    <%= form.label :start_time %><br>
    <%= form.datetime_select(:start_time, {start_hour: 7,end_hour: 20,:minute_step => 30, :ampm => true}) %>
  </div>

  <div class="form-group">
    <%= form.label :end_time %> <br>
    <%= form.datetime_select(:end_time,{start_hour: 7,end_hour: 20,:minute_step => 30, :ampm => true}) %>
  </div>

  <div class="form-group">
    <%= form.label :user_id %><br>
    <%= form.select(:user_ids, User.where.not(email: current_user.email).map {|user| [user.email, user.id]}, {}, id: "event_user_ids", :multiple => true, :class => 'form-control js-selectable') %>
  </div>

  <div class="form-group">
    <%= form.label :room_id %>
    <select name="meeting[room_id]" class ='form-control'>
    <% Room.all.each do |room| %>
        <option value="<%= room.id %>"><%= room.name %></option>
    <% end %>
</select>
  </div>

  <div class="form-group">
    <%= form.submit({:class => 'btn btn-success btn-block'}) %>
  </div>
<% end %>
<%= link_to 'Back', meetings_path, class: 'btn btn-info btn-block' %>
  </div>
</div>

app/views/meetings/_meetings_na.html.erb
<div class = 'rounded border border-grey-light text-center refact'>
    <%= image_tag "no-schedule.svg", alt: "Schedule", width: 600, class: 'mb-2' %>
    <h1 class = 'text-indigo-darker text-2xl mb-6'>Yoho!!! No meetings for you yet.</h1>
    <div class = 'buttons ml-4 mr-4'>
    <%= link_to 'Schedule  a meeting', new_meeting_path, class: 'btn btn-dark mb-3' %>
    <%= link_to 'Rooms', rooms_path, class: 'btn btn-dark mb-3' if current_user.admin?%>
    </div>
</div>

app/views/meetings/_meetings_page.html.erb
<nav class="bg-white mb-4 shadow rounded">
  <div class = 'buttons ml-4 mr-4 my-2'>
    <%= link_to 'Schedule a Meeting', new_meeting_path, class: 'btn btn-success mb-3' %>
    <%= link_to 'Calendar Mode', meetings_calendar_path, class: 'btn btn-success mb-3' %>
    <%= link_to 'Rooms', rooms_path, class: 'btn btn-dark mb-3' if current_user.admin?%>
    </div>
</nav>

<div class="bg-white p-10 border rounded">
  <div id="all-meetings" class="tab-panel">
     <h1 class='text-center'>Meetings</h1>            
  </div>
<ul class="nav nav-tabs" id="myTab" role="tablist">
  <li class="nav-item">
    <a class="nav-link" id="previous-tab" data-toggle="tab" href="#home" role="tab" aria-controls="home" aria-selected="false">Previous</a>
  </li>
  <li class="nav-item">
    <a class="nav-link active" id="today-tab" data-toggle="tab" href="#profile" role="tab" aria-controls="profile" aria-selected="true">Today</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" id="upcoming-tab" data-toggle="tab" href="#contact" role="tab" aria-controls="contact" aria-selected="false">Upcoming</a>
  </li>
</ul>
<div class="tab-content" id="myTabContent">
  <div class="tab-pane fade show active" id="home" role="tabpanel" aria-labelledby="home-tab">
  <table class = 'table'>
            <thead class= 'thead-dark'>
                <tr>
                <th scope = 'col'>Name</th>
                <th scope = 'col'>Begins at</th>
                <th scope = 'col'>End at</th>
                <th scope = 'col'>Room</th>
                <th scope = 'col'>Action</th>
                </tr>
            </thead>

            <tbody>
                <% @meetings_previous.each do |meeting| %>
                <tr>
                    <td><%= meeting.name %></td>
                    <td><%= readable_time(meeting.start_time) %></td>
                    <td><%= readable_time(meeting.end_time) %></td>
                    <td><%= meeting.room.name %></td>
                    <td><%= link_to "Cancel Meeting", meeting, method: :delete, data: { confirm: "Are you sure? There are no refunds." }, class: "btn btn-warning" %></td>
                </tr>
                <% end %>
            </tbody>
        </table>
  </div>
  <div class="tab-pane fade" id="profile" role="tabpanel" aria-labelledby="profile-tab">
  <table class = 'table'>
            <thead class= 'thead-dark'>
                <tr>
                <th scope = 'col'>Name</th>
                <th scope = 'col'>Begins at</th>
                <th scope = 'col'>End at</th>
                <th scope = 'col'>Room</th>
                <th scope = 'col'>Action</th>
                </tr>
            </thead>

            <tbody>
                <% @meetings_today.each do |meeting| %>
                <tr>
                    <td><%= meeting.name %></td>
                    <td><%= readable_time(meeting.start_time) %></td>
                    <td><%= readable_time(meeting.end_time) %></td>
                    <td><%= meeting.room.name %></td>
                    <td><%= link_to "Cancel Meeting", meeting, method: :delete, data: { confirm: "Are you sure? There are no refunds." }, class: "btn btn-warning ml-4" %></td>
                </tr>
                <% end %>
            </tbody>
        </table>
  </div>
  <div class="tab-pane fade" id="contact" role="tabpanel" aria-labelledby="contact-tab">
  <table class = 'table'>
            <thead class= 'thead-dark'>
                <tr>
                <th scope = 'col'>Name</th>
                <th scope = 'col'>Begins at</th>
                <th scope = 'col'>End at</th>
                <th scope = 'col'>Room</th>
                <th scope = 'col'>Action</th>
                </tr>
            </thead>

            <tbody>
                <% @meetings_upcoming.each do |meeting| %>
                <tr>
                    <td><%= meeting.name %></td>
                    <td><%= readable_time(meeting.start_time) %></td>
                    <td><%= readable_time(meeting.end_time) %></td>
                    <td><%= meeting.room.name %></td>
                    <td><%= link_to "Cancel Meeting", meeting, method: :delete, data: { confirm: "Are you sure? There are no refunds." }, class: "btn btn-warning ml-4" %></td>
                </tr>
                <% end %>
            </tbody>
        </table>
  </div>
</div>

app/views/meetings/calendar.html.erb
<div class = 'calendar-view'>
<%= month_calendar events: @meetings do |date, meetings| %>
  <%= date %>
  <% meetings.each do |meeting| %>
    <div class = 'meeting-link'>
      <%= link_to meeting.name, meeting, class: "link" %>
    </div>
  <% end %>
<% end %>
</div>

app/views/meetings/edit.html.erb
<h1>Editing Meeting</h1>

<%= render 'form', meeting: @meeting %>

<%= link_to 'Show', @meeting %> |
<%= link_to 'Back', meetings_path %>

app/views/meetings/index.html.erb
<% unless current_user.meetings.any? %>
    <%= render 'meetings_na' %>
    <% else%>
    <%= render 'meetings_page' %>
<%end%>

app/views/meetings/new.html.erb
<%= render 'form', meeting: @meeting %>

app/views/meetings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @meeting.name %>
</p>

<p>
  <strong>Start time:</strong>
  <%= @meeting.start_time %>
</p>

<p>
  <strong>End time:</strong>
  <%= @meeting.end_time %>
</p>

<p>
  <strong>Room:</strong>
  <%= @meeting.room_id %>
</p>

<%= link_to 'Edit', edit_meeting_path(@meeting) %> |
<%= link_to 'Back', meetings_path %>

app/views/rooms/_form.html.erb
 <% if room.errors.any? %>
    <div id="error_explanation">
        <% room.errors.full_messages.each do |message| %>
          <div class = 'alert alert-danger'><%= message %></div>
        <% end %>
    </div>
  <% end %>
<div class="card" style="width: 20rem;">
  <div class="card-body">
    <h4 class="card-title text-center"><strong>Create Room</strong></h4>
    <%= form_with(model: room, local: true) do |form| %>
  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :capacity %>
    <%= form.number_field :capacity, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.submit class: 'btn btn-success btn-block'%>
  </div>
<% end %>
<%= link_to 'Back', rooms_path, class: 'btn btn-info btn-block'%>
  </div>
</div>

app/views/rooms/edit.html.erb
<h1>Editing Room</h1>

<%= render 'form', room: @room %>

<%= link_to 'Show', @room %> |
<%= link_to 'Back', rooms_path %>

app/views/rooms/index.html.erb
<h1 class = 'text-center'>Rooms Available</h1>

<table class = 'table'>
  <thead class= 'thead-dark'>
    <tr>
      <th scope = 'col'>Name</th>
      <th scope = 'col'>Capacity</th>
      <th scope = 'col'>Action</th>
    </tr>
  </thead>

  <tbody>
    <% @rooms.each do |room| %>
      <tr>
        <td><%= room.name %></td>
        <td><%= room.capacity %></td>
        <td><%= link_to 'Destroy', room, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<div class = 'buttons'>

<%= link_to 'New Room', new_room_path, class: 'btn btn-dark' %>

</div>

app/views/rooms/new.html.erb
<%= render 'form', room: @room %>

app/views/rooms/show.html.erb
<div class ='rooms-page'>
  <p>
  <strong>Name:</strong>
  <%= @room.name %>
</p>

<p>
  <strong>Capacity:</strong>
  <%= @room.capacity %>
</p>

<%= link_to 'Edit', edit_room_path(@room), class: 'btn btn-dark' %> |
<%= link_to 'Back', rooms_path %>
</div>

app/views/simple_calendar/_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <span class="calendar-title"><%= t('date.month_names')[start_date.month] %> <%= start_date.year %></span>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table ">
    <thead class = 'thead-dark'>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <%= content_tag :tr, class: calendar.tr_classes_for(week) do %>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &block) %>
              <% else %>
                <% block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/simple_calendar/_month_calendar.html.erb
<div class = 'container feat-calendar'>
  <div class="simple-calendar">
  <div class="calendar-heading text-center mb-2">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view, class: 'btn btn-primary' %>
    <span class="calendar-title"><strong><%= t('date.month_names')[start_date.month] %> <%= start_date.year %></strong></span>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view ,  class: 'btn btn-primary' %>
  </div>

  <table class="table">
    <thead class = 'thead-dark'>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &block) %>
              <% else %>
                <% block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>  
</div>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">

    <div>
      <% resource.errors.full_messages.each do |message| %>
        <div class= 'alert alert-warning'><%= message%></div>
      <% end %>
    </div>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name), class: 'btn btn-success btn-block' %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name), class: 'btn btn-primary btn-block' %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>